### PR TITLE
Update the stage number of decorator proposal

### PR DESCRIPTION
**Pull request by Ahmed-Hakeem**

### CODE REVIEW

**Comment by orta** [comment]
Thanks - dupe of #2348

**Comment by Ahmed-Hakeem** [comment]
> Thanks - dupe of #2348 

My pleasure

**Comment by Ahmed-Hakeem** [comment]
> Thanks - dupe of #2348

It's pending on what in this https://github.com/microsoft/TypeScript-Website/pull/2348

**Comment by jakebailey** [comment]
See: https://github.com/microsoft/TypeScript-Website/pull/2348#issuecomment-1552220140

**Pull request closed without merging**
