### PR TITLE
PB-BR Version of TS for the New Programmer.md

### PR DESCRIPTION
**Pull request by tomashugo**
PB-BR Version of TS for the New Programmer.md

### CODE REVIEW

**Comment by orta** [comment]
The files should be using `/pt/` - not `/pt-br/` which is causing your CI issues 👍🏻

**Comment by tomashugo** [comment]
> The files should be using `/pt/` - not `/pt-br/` which is causing your CI issues 👍🏻

Ok, I've updated the file with `/pt/`.
Thanks.

**Comment by orta** [comment]
And the filename: `packages/documentation/copy/pt-BR/get-started/TS para o Novo Programador.md` -> `packages/documentation/copy/pt/get-started/TS para o Novo Programador.md`

**Review by tomashugo — COMMENTED** [review]
ok

**Comment by orta** [comment]
This PR looks right to me, @khaosdoctor can you give it a review and if it still is red, I'll self-merge it when I switch to the new repo with https://github.com/microsoft/TypeScript-Website/issues/1480

**Review by khaosdoctor — APPROVED** [review]

**Comment by khaosdoctor** [comment]
lgtm

**Comment by khaosdoctor** [comment]
It seems finet o me too

**Pull request merged**
