### PR TITLE
MigrationStories: fixes the loading of the info next to the migration…

### LINKED ISSUE #555: When loading the homepage from going to another site, the info next to the migration stories doesn't load
**Bug:**

Screen Shot 2020-05-08 at 12 52 59 PM

Go to any page, then click the TypeScript logo in the top-left.

### PR DESCRIPTION
**Pull request by dandelionadia**
## Motivation:

When loading the homepage after gone to another site, the info next to the migration stories doesn't load.

## Changes:

- Adds opacity  animation to the info block.
- Deleted firstRun and everything connected to it (timeout, props)

## GitHub:

Fixes #555

### CODE REVIEW

**Comment by dandelionadia** [comment]
Please, can you tell me why it's not success for me in "Contributor License Agreement"?

**Comment by orta** [comment]
Hrm, I do not know - I've never heard of it failing before. Will ask internally.

**Comment by orta** [comment]
We don't know, can you try again?

**Comment by orta** [comment]
Thanks @dandelionadia - this got a bit of a re-write with the new homepage and I don't think it's too relevant anymore

**Pull request closed without merging**
