### PR TITLE
Update Modules.md

### PR DESCRIPTION
**Pull request by izadi-abraham**
The import was incorrectly importing `math.js` instead of `math.ts` file.

### CODE REVIEW

**Comment by jakebailey** [comment]
This code is correct as-is. TypeScript does not rewrite import paths so this code would be unlikely to work if emitted.

Note the other imports below that code block which also use the `.js` extension.

Consider taking a look at https://www.typescriptlang.org/docs/handbook/modules/theory.html.

**Comment by izadi-abraham** [comment]
Ok, so then this desctription in the line 182 should be modified and be `math.js`, because it is referring to this code, right?:<br>
image

**Comment by jakebailey** [comment]
I'm not seeing the inconsistency; a `.ts` file compiles to a `.js` file, the sentence is just talking about the code as it was written in originally source

**Comment by izadi-abraham** [comment]
> I'm not seeing the inconsistency; a `.ts` file compiles to a `.js` file, the sentence is just talking about the code as it was written in originally source

You are right, it was all my own confusion. Sorry for the inconvenience.

**Pull request closed without merging**
