### PR TITLE
imporve the translate about tools in Chinese Language

### PR DESCRIPTION
**Pull request by bestony**
tools in Chinese is "工具", not "游乐场"(Playground)

### CODE REVIEW

**Comment by orta** [comment]
Thanks!

**Comment by orta** [comment]
@kingwl what do you think about this ^

**Comment by Kingwl** [comment]
I prefer '工具链' insted of '工具'

**Comment by bestony** [comment]
updated

**Review by Kingwl — APPROVED** [review]
LGTM

**Pull request merged**
