### PR TITLE
change dark-mode playground comment color

### PR DESCRIPTION
**Pull request by R99bbit**
@orta
HI, i'm contributed on this issue : #351 

i have prepared before-after screenshots for comparison of the changes(below is before-after).

## BEFORE
image

## AFTER
Untitled

i think that comments look better than before

if u have any opinion, plz feedback via "comments"

### CODE REVIEW

**Review by SMAKSS — COMMENTED** [review]
Hi there, thanks for the PR.

According to the Color Contrast Accessibility Validator listed by the [W3C](https://www.w3.org/WAI/ER/tools/), it gets a better score than the previous one. here's the [before](https://color.a11y.com/ContrastPair/?bgcolor=1e1e1e&fgcolor=919441) and [then](https://color.a11y.com/ContrastPair/?bgcolor=1e1e1e&fgcolor=7caf3d) comparison.

The point is, it is still failing on WCAG AAA standard for normal text size, but in the overall comparison, it is working better than the previous one.

**Comment by R99bbit** [comment]
@SMAKSS  @orta 

highly appreciate for your review :)

i am very happy to know that there was such an validator(Color Contrast Accessibility Validator suggested by the W3C)

if I had known there was such a good system, I would have used it.

anyway, I decided to refer back to the validator and change it to a color that looks better than before

## I SUGGESTED : https://color.a11y.com/ContrastPair/?bgcolor=1e1e1e&fgcolor=7caf3d
image

---

## IMPROVEMENT : https://color.a11y.com/ContrastPair/?bgcolor=1e1e1e&fgcolor=8CFF00
image

---

i will change to a commit with the improved color applied

can i merge the branch if it resonable?

thanks!

**Comment by orta** [comment]
I like the first one 👍🏻, we're not aiming for AAA compliance - comments should be more subtle than actual code and I'm pretty sure neon green is going to be distracting 😉

**Comment by R99bbit** [comment]
@orta


> I like the first one 👍🏻, we're not aiming for AAA compliance - comments should be more subtle than actual code and I'm pretty sure neon green is going to be distracting 😉



I think so too. 

Comments shouldn't hurt the clarity of other keywords.

So I'll change the commit back to the first one

here is <a href="https://github.com/microsoft/TypeScript-Website/pull/1398/commits/b5adf61a56370508b9ac7f4439aca3bc904653a5">commit</a>

thanks! 😀

**Comment by orta** [comment]
Thanks

**Pull request merged**
