### PR TITLE
Apply an inline code styling for "switch" word

### PR DESCRIPTION
**Pull request by SiarheiBobryk**

### CODE REVIEW

**Review by orta — APPROVED** [review]
👍🏻 thanks - I think you duplicated this PR BTW

**Comment by SiarheiBobryk** [comment]
🤔
Maybe I missed something. Which PR are you referring to?

**Comment by orta** [comment]
https://github.com/microsoft/TypeScript-Website/pull/2665

`<edit>`Ah, they're just really closely named!`</edit>`

**Comment by SiarheiBobryk** [comment]
Yep, closely named. It's the same fix, but for the different parts of the docs.

**Comment by SiarheiBobryk** [comment]
@orta I see that tests are "Waiting for status to be reported (Required)" 🤔

Please tell me how can I fix that.

**Comment by orta** [comment]
Someone with write access needs to hit the button which lets CI run for you, it's not on you to do anything 👍🏻

**Review by jakebailey — APPROVED** [review]

**Pull request merged**
