### PR TITLE
Add link to Utility Types page

### PR DESCRIPTION
**Pull request by karlhorky**
Closes microsoft/TypeScript-Handbook#994
Closes microsoft/TypeScript-Handbook#1037

### CODE REVIEW

**Comment by orta** [comment]
👍

**Comment by karlhorky** [comment]
Cool, thanks for merging!

Looks like those other two issues will need to be closed by hand, for whatever reason. 🤔

**Comment by orta** [comment]
Once I'm convinced the deploy is gonna work, yep - still waiting http://testsite-typescript-41eeb979-7eaa-4c74-9d47-9d182c7b61ab.azurewebsites.net/docs/home.html

**Comment by orta** [comment]
confirmed 

Screen Shot 2019-07-03 at 11 58 55 AM

**Comment by karlhorky** [comment]
Ah, missed another issue that can be closed, can you do that @orta?

https://github.com/microsoft/TypeScript-Handbook/issues/945

**Pull request merged**
