### PR TITLE
Return a promise from ATA

### PR DESCRIPTION
**Pull request by melbourne2991**
This does a couple of things:

- More ergonomic
- Know when a specific type request has completed. (Current finish event is insufficient, doesn't tell you which request is completed and is never called if the provided source code has no imports).

### CODE REVIEW

**Comment by orta** [comment]
Seems reasonable to me, I'd recommend also bumping the package json version so when the PR is merged it will also release 👍🏻

**Comment by melbourne2991** [comment]
@microsoft-github-policy-service agree

**Comment by melbourne2991** [comment]
> Seems reasonable to me, I'd recommend also bumping the package json version so when the PR is merged it will also release 👍🏻

Done 👍

**Review by jakebailey — APPROVED** [review]
LGTM but will merge/release this with the other PRs that require package publishes.

**Comment by jakebailey** [comment]
With bump versions with #2904 to minimize the waiting within the current infrastructure.

**Review by jakebailey — APPROVED** [review]

**Pull request merged**
