### PR TITLE
Update yarn

### PR DESCRIPTION
**Pull request by andrewbranch**

### CODE REVIEW

**Comment by orta** [comment]
I hit the same thing in https://github.com/microsoft/TypeScript-Website/pull/2477 - I think there's something strange going on with webpack ( https://github.com/webpack/webpack/issues/5423 / https://github.com/azu/rc-config-loader/issues/2 seems pretty similar ) but it's hard to see why a yarn upgrade would trigger it

**Comment by andrewbranch** [comment]
Hm, that’s frustrating. @orta how do you usually update package.json versions of packages in the monorepo? All I was trying to do here was ultimately ship a new patch version of @typescript/vfs, which led me to try `yarn version patch`, which wasn’t working in that RC.

**Comment by orta** [comment]
If you change the version number manually it will automatically deploy when pushed, it uses [pleb](https://github.com/wixplosives/pleb) on a merge to the [v2 branch](https://github.com/microsoft/TypeScript-Website/blob/v2/.github/workflows/v2-merged-staging.yml#L62-L67) - this is how I did it

**Comment by orta** [comment]
( I take it back, my update to main was green on that other PR if you want to take it anyway )

**Comment by andrewbranch** [comment]
I think I fixed it

**Comment by andrewbranch** [comment]
(playwright is unrelated, but I couldn’t build locally without updating)

**Comment by andrewbranch** [comment]
Well, playwright update breaks CI. Guess building locally and in Actions is too much to ask.

**Comment by andrewbranch** [comment]
Thanks for the help, @orta and @jakebailey!

**Pull request merged**
