### PR TITLE
Added Dockerfile for TypeScriptLang-Org

### PR DESCRIPTION
**Pull request by MatanelGordon**
This changes consists of 3 files:
Dockerfile - an actual working dockerfile
.dockerignore - a complementary file to deal with Dockerfile
README - added a sentence under `yarn start` that this deployment is also available via Docker

### CODE REVIEW

**Comment by jakebailey** [comment]
I don't know why we need this. The website is solely published via Azure Static Web Apps, by our team.

**Comment by MatanelGordon** [comment]
@jakebailey I needed to run the docs locally on my VM since I am in a closed network. Using docker seems to be the right choice for a case like this.

**Comment by MatanelGordon** [comment]
@microsoft-github-policy-service agree

**Comment by jakebailey** [comment]
I don't think we're going to take this; the right thing to do here is to update https://github.com/microsoft/TypeScript-Website/tree/v2/.devcontainer to have the right node version (like https://github.com/microsoft/TypeScript/tree/main/.devcontainer)

**Review by jakebailey — CHANGES_REQUESTED** [review]
See above.

**Pull request closed without merging**
