### PR TITLE
Sidebar: makes the navigation sticky

### LINKED ISSUE #78: Make the sub-navigation on TypeScript documentation sticky
## Search Terms

documentation sticky nav

## Suggestion

Make the sub-navigation on TypeScript docs (https://www.typescriptlang.org/docs/home.html) sticky so that it follows you down the page. Alternatively (or in addition), add navigation links to the bottom of pages to move next.

## Use Cases

I'm currently reading through the TypeScript docs and a minor frustration I've noticed is that I need to scroll back to the top when finishing a page so that I can move to the next one.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### PR DESCRIPTION
**Pull request by dandelionadia**
## Motivation

- Navigation does not  follow you when you scroll down the page.

## Changes

- I make the navigation sticky

## GitHub

- Fixes #78 

Annotation 2020-06-22 121154

### CODE REVIEW

**Comment by orta** [comment]
Very cool

Does this scroll internally correctly? E.g. if the menu is overflowing can I scroll it on the screen?

**Comment by dandelionadia** [comment]
@orta No, it's not, but I will try to do it.

**Comment by dandelionadia** [comment]
scrollable

**Comment by orta** [comment]
rockin' - I've given this a run locally and it looks good to me. Thanks!

**Pull request merged**
