### PR TITLE
Slightly improve awaited docs

### PR DESCRIPTION
**Pull request by holgergp**
Hi all!

thanks for the awesome new release!

I stumbled over the docs of the new `Awaited`-Type. And to be honest, I do not quite understand those. 
This PR tries to "fix" the second-to-last paragraph, where I fail to understand its intention completely 🤷‍♂️ . But that may just be my lack of english mother tongue.

Cheers

Holger

### CODE REVIEW

**Comment by orta** [comment]
Cool, looks reasonable to me 👍🏻

**Comment by holgergp** [comment]
Nice! Thanks!

**Comment by holgergp** [comment]
I think there is still some room for improvement in the docs here. At least I struggle to understand the concept here. 🤷‍♂️ (But that may be sth for a separate PR).
Things I've been stumbling over this far:
- `Awaited` is _not_ the Return type of an async function. That was my first impression. That Return Type still is `Promise<T>`. 
- `Awaited` can be used in (maybe rare) occasions, where I want to explicitly type the returned value of an awaited call.
- `Awaited` then helps me to avoid maybe nested/recursive Promises: e.g `Promise<Promise<string>>`
  - As a sidenote: I even struggled to find an example where I can construct such nested Promise construct. Maybe a hint here may be helpful to others to.
- The second code example does not even mention the `Awaited` type. I would have find it easier to understand if it would have been explicitly stated. Maybe another example would help here.
Maybe something like this (if I have understood it correctly....)

<code>

const pipe = (f, g, h) => (input) => h(g(f(input)));

const thirdAsyncFn = async (): Promise`<string>` => {
    return '3';
};

const secondAsyncFn = async (): Promise`<string>`  => {
    return '2';
};

const firstAsyncFn = async (): Promise`<string>`  => {
    return '1';
};
const pipedFn = pipe(firstAsyncFn, secondAsyncFn, thirdAsyncFn);

const returnedValue1: Promise<Promise<Promise`<string>`>> = pipedFn(2);

const returnedValue2: Awaited<Promise`<string>`> = pipedFn(2);

</code>

**Comment by holgergp** [comment]
I've created a separate Issue for this: https://github.com/microsoft/TypeScript-Website/issues/2178

**Pull request merged**
