### PR TITLE
Adds the codeowners action for offering the ability to merge PRs

### PR DESCRIPTION
**Pull request by orta**
Using https://github.com/orta/code-owner-self-merge to let people merge PRs to their translations without waiting on me

/cc @khaosdoctor @danilofuchs  @sasurau4 @Quramy @Naturalclar @Takepepe  @KingDarBoja @Kingwl

### CODE REVIEW

**Comment by danilofuchs** [comment]
@orta I tried leaving a review at https://github.com/microsoft/TypeScript-Website/pull/892 with `LGTM`, but no Action was triggered

**Comment by orta** [comment]
That's a review, not a comment - I'll add support for that

**Comment by orta** [comment]
It should handle that now, assuming I understand the semver in GH actions

**Comment by danilofuchs** [comment]
I could get it to trigger by commenting, but it looks like it is checking to see if the PR creator has merge access, instead of the approver:
https://github.com/microsoft/TypeScript-Website/runs/982690050?check_suite_focus=true

**Comment by khaosdoctor** [comment]
Awesome! This will make things a LOT easier!

**Comment by khaosdoctor** [comment]
I reviewed #815 but it seems not to merge 🤔 

--- EDIT

I commented again, it merged. Does it only works on single comments?

**Comment by orta** [comment]
It might only work on single comments? Will try next time

**Pull request merged**
