### PR TITLE
stick the documentation contents nav sidebar at one place on scroll

### PR DESCRIPTION
**Pull request by arihantverma**
stick the documentation contents nav sidebar at one place when the page is scrolled and make it scrollable

ts-website-enhancement

### CODE REVIEW

**Comment by orta** [comment]
Thanks!

This isn't quite mergable right now, because it's difficult to scroll the inside of the sidebar - for example if you wanted to scroll the sidebar further to see what's currently selected you need to scroll to the bottom of the page before the rest of the sidebar is visible.

Screen Recording 2019-10-21 17_31_14

This shows it twice:

- trying to see anything below TS 2.1
- trying to access some of the lower parts of the handbook

Any ideas on how to solve these? It feels like it's behaving differently on your gif

**Comment by IllusionMH** [comment]
Some styles tuning can prevent hiding bottom part of ToC below viewport
```diff
.toc-container {
    overflow: hidden;
    margin-right: 2em;
    width: 22em;
    padding-left: 2em;
    padding-right: 0rem;
    position: sticky;
-   top: 0;
-   height: 100vh;
+   top: 4.5rem;
+   height: calc(100vh-4.5rem);
    overflow-y: scroll;
+   overscroll-behavior-y: contain; /* prevent content scrolling when user scrolls over ToC */
}
.docs-nav {
-   margin-top: 4.5rem;
    position: relative;	
}
```

But I haven't checked mobile version

**Comment by IllusionMH** [comment]
@orta top of the `.toc-container` block and top arrow will be hidded under header, because `top` is less then header height. Also this adds empty space at the bottom.
image

IMHO it looks better if `top` matches height of the header and `margin-top` is removed or decreasd for `.docs-nav`
image

**Comment by orta** [comment]
Hey folks - thanks for putting in the time! The v1 version of the website is likely on it's last week or two now - so I'm going to close this

**Pull request closed without merging**
