### PR TITLE
Adds custom config for GitHub CodeSpaces

### PR DESCRIPTION
**Pull request by khaosdoctor**
GH Codespaces is out for a lot of people (including me) and one of the cool features it has is too apply custom configs to different repos. 

I thought this could make the onboarding process easier, so I created the `.devcontainer` folder following [the default TS container template from MS](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/typescript-node-14) to integrate in codespaces.

This container:

- Comes with Node 14 and TS
- Install yarn globally
- Installs Code Spell Checker extension for translating purposes
  - It'd be nice to suggest other extensions based on the language the person is translating/using
- Runs `yarn install` and `yarn bootstrap` after start
- Forwards port `8000` to the client

### CODE REVIEW

**Comment by khaosdoctor** [comment]
CC @orta

**Comment by orta** [comment]
Cool, this looks good to me 👍

**Comment by orta** [comment]
Does this need some kind of thing to run `yarn start`? or would it be normal to expect someone to run that themselves?

**Comment by orta** [comment]
Eh, let's just see

**Comment by khaosdoctor** [comment]
> Does this need some kind of thing to run `yarn start`? or would it be normal to expect someone to run that themselves?

There's a `postCreateCommand` that's run once the codespace is created, so it _should_ create the whole space automagically

**Pull request merged**
