### PR TITLE
A note about the "in" operator

### PR DESCRIPTION
**Pull request by SiarheiBobryk**

### CODE REVIEW

**Review by orta — APPROVED** [review]
Looks reasonable to me

**Comment by SiarheiBobryk** [comment]
@orta, the second approval is required (I'm a "first-time contributor"). Could you please ping someone and ask for a review?

**Comment by SiarheiBobryk** [comment]
One more approval is required. Please review 🙂

**Comment by jakebailey** [comment]
It's a bit unfortunate that this is then the first mention of "prototype chain" on the page, where the existing code which mentions it makes sure to say "don't worry about what that is".

Is it worth mentioning at all?

**Review by jakebailey — CHANGES_REQUESTED** [review]
^

**Comment by SiarheiBobryk** [comment]
> It's a bit unfortunate that this is then the first mention of "prototype chain" on the page, where the existing code which mentions it makes sure to say "don't worry about what that is".

> Is it worth mentioning at all?

I'd say so, but I don't insist.

**Review by jakebailey — APPROVED** [review]

**Pull request merged**
