### PR TITLE
Translate handbook

### PR DESCRIPTION
**Pull request by kimuradev**
My first humble contribution :)

@khaosdoctor , @danilofuchs, @orta

### CODE REVIEW

**Review by danilofuchs — APPROVED** [review]
:rocket:

**Review by khaosdoctor — APPROVED** [review]

**Comment by khaosdoctor** [comment]
LGTM @orta

**Comment by danilofuchs** [comment]
I just found out that these files must be imported in a new `packages/typescriptlang-org/src/copy/pt.ts` file. I created it on https://github.com/microsoft/TypeScript-Website/pull/822

**Comment by orta** [comment]
👍 yeah, these ones don't automagically appear unlike the rest (they also live in browser land so I can't use the fs to look them up)

**Comment by orta** [comment]
Let's not have it be blocked on that, it's easy to add in the future, great work - thanks for the contribution!

**Pull request merged**
