### PR TITLE
docs(i18n-id): translate disableReferencedProjectLoad.md, disableSizeLimit.md, disableSolutionSearching.md, and several config into Indonesia

### PR DESCRIPTION
**Pull request by R1dwanMaulana**
## Overview

This is part of #938 

## Changes

Translate the following files
- [x] disableReferencedProjectLoad.md
- [x] disableSizeLimit.md
- [x] disableSolutionSearching.md

### CODE REVIEW

**Comment by AMashoshyna** [comment]
@R1dwanMaulana Hi! Looks like we have and issue with CODEOWNERS file. I was accidentally assigned to code-review Indonesian version. Opened a PR with a fix: https://github.com/microsoft/TypeScript-Website/pull/1161

@jefrydco @nusendra @mazipan @mandaputtra FYI

**Comment by mandaputtra** [comment]
@R1dwanMaulana you can create pull request again after the fix get merged, for now just wait or you can open this pull request again we will check and @AMashoshyna will help us merge this translation. Thanks.

IMO better wait till fix get merged.

**Comment by R1dwanMaulana** [comment]
ok

**Comment by R1dwanMaulana** [comment]
still in trouble?

**Comment by AMashoshyna** [comment]
Yep, [PR](https://github.com/microsoft/TypeScript-Website/pull/1161) still open. But I can approve the PR with "LGTM", as @mandaputtra suggested

**Comment by AMashoshyna** [comment]
Omg, I'm sorry. I did not mean to actually merge the PR. Soo sorry.
FYI @jefrydco @nusendra @mazipan @mandaputtra

**Comment by mandaputtra** [comment]
No problem @AMashoshyna  :ok_hand: I will fix it later. I guess the bot need some improvement :laughing:

**Comment by R1dwanMaulana** [comment]
need bot repair 😅

**Comment by orta** [comment]
ha - looks like we didn't add the prefixes paths here - https://github.com/microsoft/TypeScript-Website/blob/23d08a49a912f1fdb7628a907c7c8941a02fe584/.github/CODEOWNERS#L46-L50

**Comment by jefrydco** [comment]
@orta Yup, this is the fix for that https://github.com/microsoft/TypeScript-Website/pull/1161

**Pull request merged**
