### PR TITLE
fix release notes navigation wrong link

### PR DESCRIPTION
**Pull request by holynewbie**
ts

fix navigation wrong link

### CODE REVIEW

**Comment by orta** [comment]
Thanks!

**Comment by orta** [comment]
Thanks!

**Comment by robinvw1** [comment]
When will this fix for the broken link be deployed? According to the README, deployment is automatic on merging with `master`. When looking at GitHub actions, I can see it did deploy for staging but not yet for production.

**Comment by orta** [comment]
Both sites are deployed with the fix

**Pull request merged**
