### PR TITLE
Add exporter for typescript-eslint.io/play to the playground

### LINKED ISSUE #2114: Idea: playground plugin for running typescript-eslint
**Improvement Idea:** Add a plugin that loads ESLint into the playground with typescript-eslint

**Why:**

To start, there's discussion of building a whole typescript-eslint playground in https://github.com/typescript-eslint/typescript-eslint/issues/168 and https://github.com/typescript-eslint/typescript-eslint/pull/3147. This would both save a ton of infrastructure-y work and let typescript-eslint use "the" standard TypeScript playground.

Additionally, I often use the playground to share examples of _"why aren't these types working?"_ investigations. It'd be really nice to be able to add [eslint-plugin-expect-type](https://github.com/JoshuaKGoldberg/eslint-plugin-expect-type).

**Alternative ideas:**

Well, a few folks have built their own (e.g. https://yeonjuan.github.io/typescript-eslint-demo), but that's a lot of work...

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
Fixes #2114 (roughly).

### CODE REVIEW

**Review by orta — APPROVED** [review]
Yep, looks right to me 👍🏻

**Comment by JoshuaKGoldberg** [comment]
Err @orta I just stumbled back onto this - do you know who I should ping to ask about it getting merged (or not)? Is it you?

**Comment by orta** [comment]
Given https://github.com/microsoft/TypeScript-Website/issues/2804 - you're probably better off closing IMO

**Comment by JoshuaKGoldberg** [comment]
rip

**Pull request closed without merging**
