### PR TITLE
[GH-1655] Docs: Convert Twoslash inline results to not just be a comment 

### LINKED ISSUE #1655: Docs: Convert Twoslash inline results to not just be a comment
**Page URL:** All docs pages

**Issue:** 

Today the way we represent the inline LSP queries is via ASCII compatible UI:

```ts
type Greeting = "Hello, world"
type QuietGreeting = Lowercase<Greeting>
//   ^ = type QuietGreeting = "hello, world"

type ASCIICacheKey<Str extends string> = `id-${Lowercase<Str>}`
type MainID = ASCIICacheKey<"MY_APP">
//   ^ = type MainID = "id-my_app"
```

This was the cheapest way to test out the idea, and it was good enough for shipping:

Screen Shot 2021-03-11 at 6 54 20 AM

**Recommended Fix:** 

I think we should _visually_ distinguish these callouts as not living in the code more

Screen Shot 2021-03-11 at 6 55 23 AM

In rough:

 - Underline the selected identifier
 - Center arrow under the underline
 - Align text with the left edges of the identifier 
 - Don't require JavaScript to position the popover

Nearly all this work will live in shiki-twoslash (+ some CSS)

### PR DESCRIPTION
**Pull request by hahmadia**
Fixes https://github.com/microsoft/TypeScript-Website/issues/1655

Hi @orta,

I've done the very best I can and this is what I've been able to achieve. Hoping you can help me out. My biggest challenge is being able to left align the textbox with the identifier. I couldn't figure it out. Also, need a bit of help with the CSS. I just took some guesses but feel free to fix it up. I've spent many hours on this project so I'm hoping there is not too much that needs fixing. Thank you!

image

### CODE REVIEW

**Review by orta — APPROVED** [review]
Yeah, I don't have enough time today to dig into the details and wrap up this PR, but this is what I expected it to look like

**Comment by hahmadia** [comment]
> Yeah, I don't have enough time today to dig into the details and wrap up this PR, but this is what I expected it to look like

@orta 
Yah! That's great to hear cause I had spent a week banging my head trying to get it to look exactly like mock ups with no success 😢 but I'm happy to hear that you like it 🎉 🎉 !!!!

**Comment by hahmadia** [comment]
Is this okay to be merged? I'm just curious on what we are waiting for.

/cc @orta

**Comment by orta** [comment]
It's on me finding the time to go through it properly

**Pull request merged**
