### PR TITLE
translate locale to ko

### PR DESCRIPTION
**Pull request by voidmatcha**
en: https://github.com/microsoft/TypeScript-Website/blob/v2/packages/tsconfig-reference/copy/en/options/locale.md
related issue: #910

### CODE REVIEW

**Review by bumkeyy — APPROVED** [review]
LGTM

**Comment by orta** [comment]
Looks like the security model around GitHub reviews isn't going to work for the LGTM at the moment, I think I know how it can be improved but for now you can write a comment

**Comment by bumkeyy** [comment]
> Looks like the security model around GitHub reviews isn't going to work for the LGTM at the moment, I think I know how it can be improved but for now you can write a comment

okay 😄

**Comment by bumkeyy** [comment]
LGTM

**Pull request merged**
