### PR TITLE
Fix typo in sandbox console.log

### PR DESCRIPTION
**Pull request by tjjfvi**
(Would it be better to remove this log entirely, or is it desired?)

### CODE REVIEW

**Comment by keithlayne** [comment]
Only dirtbags don't give credit where it's due 🚎

**Comment by tjjfvi** [comment]
@keithlayne I made this PR 3 days ago

**Comment by keithlayne** [comment]
That's fake news.

**Comment by orta** [comment]
Yeah, thanks - I need to look at all this parsing business again anyway

**Pull request merged**
