### PR TITLE
Add Indonesian language to dt.ts

### PR DESCRIPTION
**Pull request by mul14**

### CODE REVIEW

**Review by SMAKSS — COMMENTED** [review]
Thank you again, but this is the same as the previous PR (#1276) that you made, so for more information please follow #938.

**Comment by mandaputtra** [comment]
You can close this @SMAKSS , it already [translated well](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/typescriptlang-org/src/copy/id/dt.ts)

**Comment by SMAKSS** [comment]
> You can close this @SMAKSS , it already [translated well](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/typescriptlang-org/src/copy/id/dt.ts)

@mandaputtra  Well, I like to, but I don't have the rights. 😄

**Comment by mandaputtra** [comment]
Haha, okay then. @orta can you help to close this pull request? Thank you in advance.

**Pull request closed without merging**
