### PR TITLE
Docs: make "The handbook.md" more readable and interesting

### PR DESCRIPTION
**Pull request by shoaibshebi**
### updated "The handbook.md" page making it more readable and consumable to get a higher pace for developers.

PR under the Issue: #2353

### CODE REVIEW

**Review by orta — CHANGES_REQUESTED** [review]
Thanks for taking a shot at improving the docs, but I don't think emoji-filled text is really the tone we use for the TypeScript docs.

**Comment by shoaibshebi** [comment]
@orta Thanks for the feedback. Firstly being a JS developer I have read all the Handbook and other docs and practiced it using Javascript and React. Then I feel it really needs the emojis due to difficulty to consume. And after spending almost 4-5 hours 🤯, on only these two pages "the handbook.md" and "the basics.md" I chose the emojies for each line after sensing the tones of lines.

So it's a humble request to you 🙏, that you can suggest the lines of doc, what changes could be made to improve it 😇. As I am on daily basics work with TS as I'm a JS developer, I found it difficult without emojis, and of course a lot of other people found, as I got the feedback from my colleagues.

**Comment by shoaibshebi** [comment]
I tried to using tech emojies, and not like only Yellow ones. But where the tone was about joy and sad I used the yellowish one as well.

So please suggest the changes 🙏, so I can follow for the next pages. As I want to update the whole handbook 📖.

Thanks

**Comment by orta** [comment]
Sure, my feedback is that I would recommend not spending more of your time on the pull request and you should probably close this because it's unlikely to get merged. 

Emojis have their place in written communication, but professional technical documentation shouldn't have an emoji per paragraph, it makes it read like a youtuber wrote it where they have to keep reacting to the words they just said to add emphasis. It's cool if that's your writing style, the internet is a big place and that allows for all sorts of ways to write - but it's not the TypeScript team's.

**Comment by shoaibshebi** [comment]
Okay, @orta. Thanks for the feedback and I will close the PR.

**Pull request closed without merging**
