### PR TITLE
Fix newline removal in twoslash inlays

### PR DESCRIPTION
**Pull request by jakebailey**

### CODE REVIEW

**Comment by orta** [comment]
I think if you want to do this, you'd need to at least make sure there is a corresponding preceding whitespace for the extra lines, or you'd probably get this:

```
console.log(a)
//                   ^? {
  a: string
}
```

**Comment by jakebailey** [comment]
I'm a little confused how the above would be possible; doesn't this remove the newlines entirely so you have to end up with `^? {  a: string  }`?

**Comment by orta** [comment]
Ah, I misread! Yeah, I could imagine this working? I'm no pro on regex

**Review by andrewbranch — APPROVED** [review]

**Comment by andrewbranch** [comment]
Haha I always wondered why those showed up

**Comment by jakebailey** [comment]
Now looking at this on the playground, and it doesn't look good at all. [Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAwg9gWzAGwsCAeAKgPigXigG8AoASAG0BpKASwDsoBrCEOAMygCUIBHAV1oAnCABNsOALoAuKFmqSA3CQC+ykiQboh7AIYBjaAGVEaABYMA5sXLs4cAPyz6-BACMIQ5WTe6hs0jIfXQAvJygAZ2AhK28VVQ1QSFhEFDQIEwRzKwIUpFR0DEzs+kscZQB6CqgagD0HEiA)

These probably should have been replaced with spaces. I didn't realize that it was being replaced with the empty string.

**Pull request merged**
