### PR TITLE
Make `elementToAppend` take priority over `domID` for sandbox configs

### LINKED ISSUE #2885: Can't use `elementToAppend` when embedding sandbox
Because `domID` in the sandbox config takes precedence over `elementToAppend`:

https://github.com/microsoft/TypeScript-Website/blob/a03790f13df45ca6302abae688432762121db3c8/packages/sandbox/src/index.ts#L147

and `domID` is always given a default of `""`:

https://github.com/microsoft/TypeScript-Website/blob/a03790f13df45ca6302abae688432762121db3c8/packages/sandbox/src/index.ts#L89

`elementToAppend` will never work

### PR DESCRIPTION
**Pull request by codetheweb**
Closes https://github.com/microsoft/TypeScript-Website/issues/2885.

### CODE REVIEW

**Review by orta — APPROVED** [review]
Looks good to me

**Review by jakebailey — APPROVED** [review]
Seems fine to me, though I'm assuming this is a part of a published package, in which case I'm holding off those kinds of PRs a little until I can... figure out how exactly to bump and publish these packages correctly.

**Comment by orta** [comment]
Merges to `v2` [run](https://github.com/microsoft/TypeScript-Website/blob/6510107ca8c114ec00967c7ec5ceabc746ca6d87/.github/workflows/v2-merged-staging.yml#L61-L66) [pleb](https://github.com/wixplosives/pleb#pleb) - which compares the versions in the package.json for any non-private package in the packages folder and then npm publishes them if that version is not present - there's a small writeup here: https://github.com/microsoft/TypeScript-Website/issues/130#issuecomment-663471663

**Comment by jakebailey** [comment]
With bump versions with #2904 to minimize the waiting within the current infrastructure.

**Review by jakebailey — APPROVED** [review]

**Pull request merged**
