### PR TITLE
Add wikipedia like popups

### PR DESCRIPTION
**Pull request by alirezaghey**
Adds popups for tsconfig links
Popup positioning is not ideal
Related to #1656

### CODE REVIEW

**Comment by orta** [comment]
This is close! I want to auto-generate the JSON object and then we're good

**Comment by orta** [comment]
There we go - thanks @alirezaghey !

**Comment by alirezaghey** [comment]
Thanks @orta, this looks amazing! I'll look into how we can add MDN and internal documentation pages according to #1656 and also how we can make the popups aware of their position on the page so that they move a little bit to the opposite side like how they do on wikipedia.

**Comment by orta** [comment]
I've left some of my ideas on the MDN and docs pages, the tricky thing is making a markdown summary but I've included a pretty reasonable idea for how that could happen.

Re: popup positioning, that's doable - it's just JavaScript and deciding which side is closest to the middle of the page and using that edge to position the popover instead of right now where it's the bottom always. I'd start with maybe doing either above or below first, and then look at left or right

**Pull request merged**
