### PR TITLE
DOM Manipulation Clarification

### PR DESCRIPTION
**Pull request by robhowe-A**
Adding parentheses clarifies statements.

### CODE REVIEW

**Comment by jakebailey** [comment]
I'm not sure that this is an improvement; it reads roughly the same to me.

**Comment by robhowe-A** [comment]
Going through the doc, I read it as ambiguous/imprecise. Id be happy to help the change, of it helps.
DOM manipulations are fairly easy, there should be nothing ambiguous at that level of interpretation. I learned much from the article.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jakebailey** [comment]
I'm not sure what we'd change it too; both before and after it refers to a code snippet above and I don't see how it can be ambigious.

**Comment by robhowe-A** [comment]
The proper grammatical implementation is to use parentheses, I'm sure I looked it up to confirm it. That's why I'm offering an improvement.

Proper scripts documents deserve proper use of grammer to avoid amiguous situations from any sense. A clearer version may be helpful to someone, so I submitted the version change.


All the best,

Robert H.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by robhowe-A** [comment]
Pushing requires testing. That appears to be without my attention?

**Pull request closed without merging**
