### PR TITLE
docs(i18n-id): translate disableSolutionSearching.md and several config section into Indonesia

### PR DESCRIPTION
**Pull request by R1dwanMaulana**

### CODE REVIEW

**Comment by orta** [comment]
This PR contains a package-lock and so it does not class as a translation PR 

/cc  @jefrydco, @nusendra, @mazipan, and @mandaputtra

**Comment by mazipan** [comment]
@R1dwanMaulana please clean up your PR.
It's no supposed to change the lockfile

**Review by mazipan — CHANGES_REQUESTED** [review]
Need to cleanup the PR

**Review by mazipan — CHANGES_REQUESTED** [review]
Need to cleanup the PR

**Comment by jefrydco** [comment]
Minta tolong lihat https://github.com/microsoft/TypeScript-Website/pull/1134#issuecomment-699263621 ya

**Pull request closed without merging**
