### PR TITLE
Migrate typescript.events to official website

### PR DESCRIPTION
**Pull request by ddprrt**
Related: Issue #63

This pull request takes all the content of https://typescript.events and moves it to https://typescriptlang.org

Changes include:
- YAML files for conferences and meetups
- Logos of conferences and meetups
   Questions:
   - Ask Meetup organisers for permission?
   - Store at a different spot?
- Changes in Markup
   - Correct headline hierarchy
   - Refactored headline stile for callouts to reusable CSS class

I took the liberty to call the headline "Connect in person" instead of "Connect offline". Offline felt a bit to sad for me :-) Let me know what you think.

Result:

localhost_3000_community_index html

Once moved I'll redirect the domain.

### CODE REVIEW

**Comment by orta** [comment]
OK - this is great! I've pushed a few minor changes (while I'm personally pumped to have TS NYC first, I think alphabetically makes it more fair)

---

I'd like to make sure every meetup on the site has a Code of Conduct. I'm happy with that metadata on an event page (like [TSNYC](https://www.meetup.com/TypeScriptNYC/events/265531686/) or on the main page like [TypeScript BR](https://www.meetup.com/typescriptbr/) ) but now is a good time to make sure the infra is in place for that. Sorry to make it block your PR though. 

- [ ] Dublin TypeScript Meetup
- [ ] London TypeScript Meetup
- [ ] Milano TS
- [ ] Sevilla TypeScript
- [ ] San Francisco TypeScript Meetup
- [x] TypeScript NYC
- [ ] Typescript Brazil Meetup
- [ ] Krakow TypeScript User Group
- [ ] TypeScript JP
- [x] Paris TypeScript
- [ ] Phoenix TypeScript
- [ ] Warsaw TypeScript
- [ ] Wroclaw TypeScript

I'm going to ping folks on twitter/email to get these added. If it takes a long time, I think it's fine for us to comment some out and I'll keep pestering. If folks have really strong opinions against a CoC, we can figure that out too.

**Comment by bcherny** [comment]
Hey there @orta! Is there a Code of Conduct you suggest we use?

**Comment by ddprrt** [comment]
No worries about the delay, I'm happy to wait for this one :-) 
I've also send a couple of mails to meetup organisers who I know and who don't have a Twitter account.

**Comment by orta** [comment]
Sure! How I did it for @cocoapods ([here](http://cocoapods.org/legal)) was to take [Conf Code of Conduct 's template](https://confcodeofconduct.com) and fill in the details like name, type of event etc. It's changed a bit since I used that template. That's because it can host a wide variety of events.

For TS NYC we opted into using the same one as most of the other NYC meetups for ease of use by adding:

> - Code of conduct: JSConf Code of Conduct

To [our event pages](https://www.meetup.com/TypeScriptNYC/events/265531686/) and making sure there's an opening slide which mentions it. It could have been on the main info page instead, like a code license, a link is enough if it's in the right place.

**Comment by giogonzo** [comment]
Hi @orta thanks for pinging us. I just added a CoC for Milano TS (https://www.meetup.com/it-IT/MilanoTS/pages/29738148/Code_of_Conduct/) which is linked from the main meetup page and future event pages. It is a translation and adaptation of https://confcodeofconduct.com

**Comment by bcherny** [comment]
Thanks @orta! CoC here: https://github.com/San-Francisco-TypeScript-Meetup/code-of-conduct, also linked from https://www.meetup.com/San-Francisco-TypeScript-Meetup/.

**Comment by karol-majewski** [comment]
Thanks @orta! [We have adopted one](https://www.meetup.com/WrocTypeScript/pages/29747057/Code_of_Conduct/) for Wrocław TypeScript.

It's also linked to on our website, https://typescript.community.

**Comment by Leko** [comment]
Hi @orta! I'm an organizer of TypeScript JP (we hold TSConf JP and TypeScript meetup in Japan).
Our CoC is here. https://typescript-jp.dev/coc/

**Comment by orta** [comment]
Alright folks, I've added links to the TypeScript community, fixed the layout, added only meetups which currently have a Code of Conduct to be on the site and it's ready to go. 

Meetup organizers: Feel free to either tell me if you add the CoC and I'll add you to the site, or make a PR to `src/_data/community/meetups.yml` and add your meetup 👍

**Comment by ddprrt** [comment]
Wohoo 💃

**Comment by dylans** [comment]
@orta CoC link added for PHX-TS. Thanks!

**Pull request merged**
