### PR TITLE
chore: fix bootstrap on windows

### PR DESCRIPTION
**Pull request by wardpeet**
I had to do 2 fixes to make `yarn bootstrap` work

1. Git should have files saved as LF so `os.EOL` doesn't work. Switching to just "\n" works.
1. cp does not exists on windows, cpy-cli can fix this. (happy to use any other package)

### CODE REVIEW

**Comment by orta** [comment]
Cool! I wonder what's up with the `yarn install` - re-running

**Comment by wardpeet** [comment]
@orta, I see that I committed a change with my prettier config. Should I revert? Are you ok with adding husky, prettier perhaps?

I'm happy to do the work

**Comment by orta** [comment]
Yeah, it's fine - that's the right prettier config, I think sometimes my editor gets confused and ships the default

**Comment by orta** [comment]
( I already have that stuff set up, but it only triggers for me )

**Comment by orta** [comment]
There we go, working fine - it was mainly just me pushing to master during work on https://github.com/microsoft/TypeScript-Website/issues/130#issuecomment-653931944

**Pull request merged**
