### PR TITLE
docs: fix language in MDN links, link sources and link anchors

### PR DESCRIPTION
**Pull request by pathliving**

### CODE REVIEW

**Comment by pathliving** [comment]
> @pathliving please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by pathliving** [comment]
Please close the pull request if it's irrelevant, or accept it. I would appreciate any feedback somebody can provide. Thanks in advance!

**Comment by jakebailey** [comment]
Why add the language code to all of these?

**Comment by pathliving** [comment]
> Why add the language code to all of these?

Thanks for your question. I understand the concerns. However, the changes are focused on improving UX and fixing some outdated URLs. This adds consistency with other links. It also addresses the issue of users who visit the documentation being defaulted to English instead of their local language - I experienced this myself when I clicked on a link and instead of opening the MDN documentation in English, I got the Ukrainian documentation, which was inconvenient because it forced me to find the language switch and change it to English

**Comment by pathliving** [comment]
@jakebailey could you please review my feedback when you have a moment? I would greatly appreciate your final decision on these documentation updates. Thank you for your time!

**Comment by jakebailey** [comment]
It's just not clear to me what the benefit is; I get that the site is in English, but if someone's translating the site automatically, it doesn't seem better to link to the wrong language again.

**Comment by pathliving** [comment]
@jakebailey you're absolutely right and I agree with you

Let's start from the beginning. When we open the `v2` branch of the current repo and search for links, we find many with the locale prefix `/en-US/`. My initial idea was to standardize the language for all links by using the `/en-US/` prefix. 

However, I understand and support your opinion on this matter

Do you have any suggestions on what might be the best course of action? Should we add the `/en-US/` prefix to the remaining links as I proposed in my pull request or would it be better to remove the language prefix from all links in the [TypeScript documentation](https://github.com/search?q=repo%3Amicrosoft%2FTypeScript-Website%20%2Fen-US%2F&type=code)?

image

**Comment by jakebailey** [comment]
It would be better remove the language prefix.

The DOM types in TS also recently dropped these prefixes.

**Pull request closed without merging**
