### PR TITLE
Should not render </tr> as code block

### PR DESCRIPTION
**Pull request by zartre**
Before: `</tr>` is rendered as a code block

Screen Shot 2564-08-31 at 20 51 29

After: `</tr>` is now part of the table's HTML

Screen Shot 2564-08-31 at 20 51 05

### CODE REVIEW

**Comment by orta** [comment]
Thanks! - These files are auto-generated, so I think it needs to be handled in the `tsconfig-reference` package in this monorepo 👍🏻

**Comment by zartre** [comment]
Thanks for pointing out. Will look into it 😀

**Comment by orta** [comment]
Ace! Thanks this looks good to me 👍🏻

**Comment by zartre** [comment]
Thanks!! 😊

**Pull request merged**
