### PR TITLE
Make tsconfig-reference display values Title Case

### PR DESCRIPTION
**Pull request by mark-wiemer**
Some values were `camelCase`, this makes all titles `Title Case`.

Found using `grep -r "display: \"[a-z]" packages/tsconfig-reference/copy/en/options`

Other minor changes auto-generated and appear to fix up whitespace

### CODE REVIEW

**Comment by mark-wiemer** [comment]
@microsoft-github-policy-service agree

**Comment by orta** [comment]
I don't think we need this, the format is made like this for both SEO, and so you can find on the page for the exact field you are looking for

**Comment by mark-wiemer** [comment]
What is the criteria for a title to be `camelCase` vs `Title Case`? It feels random

**Review by orta — APPROVED** [review]
Oh yeah, just went and looked - we have the real name value next to the title case, I bet this was probably just new flags getting added or non-complete automation - this should get merged 👍🏻

**Review by jakebailey — APPROVED** [review]
Checked the other files `tsconfig-reference` and this looks to correct an inconsistency.

**Pull request merged**
