### PR TITLE
Placedholder type search page

### LINKED ISSUE #2645: Docs: TypeSearch is down
**Page URL:** https://www.typescriptlang.org/dt/search 

navigating from https://www.typescriptlang.org/docs/handbook/declaration-files/consumption.html#searching

**Issue:** it doesn't load

Screenshot 2022-12-15 at 1 13 11 PM

**Recommended Fix:** 

some indication that this was removed intentionally

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
Fixes #2645.

I haven't been able to get this website to build locally 😡 so this is a bit of an estimation / draft for now. You'll have to let me know how it looks. 😄

### CODE REVIEW

**Comment by orta** [comment]
The local build may be fixed by #2473

**Comment by JoshuaKGoldberg** [comment]
My issues were around canvas not being able to build. I don't have access to my windows laptop just now but have been meaning to check if it's Mac specific before reporting.

**Comment by andrewbranch** [comment]
Thanks @JoshuaKGoldberg! Can you paste some of your failing build output? We’re trying to remove things that frequently cause local build issues (hence #2619), and I wasn’t aware of this one. We’ve recently had local builds working on both Mac and Windows.

**Comment by andrewbranch** [comment]
@navya9singh can you see if you’re able to check this locally? Thanks!

**Comment by andrewbranch** [comment]
Agh, the deployment isn’t going to work on PRs from forks. @orta knew this over two years ago, but Azure still hasn’t done anything about it 😠 https://github.com/Azure/static-web-apps/issues/1

**Comment by JoshuaKGoldberg** [comment]
Welp, I can't figure out why localization copy isn't working locally. But here's what I have:

Screenshot of the page with keys like dt_s_page_title instead of real text

**Comment by andrewbranch** [comment]
LGTM, ship it 🚀

**Comment by andrewbranch** [comment]
It’s previewable at https://delightful-glacier-09aa73710-pr2676.centralus.azurestaticapps.net/ (just pretend I’m a bot that commented that automatically)

**Comment by JoshuaKGoldberg** [comment]
All right, I gave up on localization and just embeddded the strings directly. If anybody can get it to work, please do 🙃

Screenshot of the page with correct text

**Comment by andrewbranch** [comment]
Thanks for your ping-patience while I use this PR to debug the preview environments workflows 😄

**Comment by andrewbranch** [comment]
Yooooo 😎

**Comment by JoshuaKGoldberg** [comment]
Will Ferrell in Elf excitedly entering a restaurant and saying "You did it!"

**Comment by andrewbranch** [comment]
The last code path to try is pushing a new commit to an already-labeled PR. After I verify that’s working, I’ll merge without localization, unless @navya9singh wants to try to figure it out. Thanks @JoshuaKGoldberg!

**Pull request merged**
