### PR TITLE
Update TS for OOPers.md

### PR DESCRIPTION
**Pull request by ododa**

### CODE REVIEW

**Comment by orta** [comment]
I can see a case for both the before and the after to be honest

**Comment by ododa** [comment]
Isn't this guide teaching TypeScript?

**Comment by orta** [comment]
Yep but TypeScript doesn't run in JavaScript engines - JavaScript does and the original wording is appropriate for that

**Comment by ododa** [comment]
Alright. I'm still convinced "TypeScript" would be a better choice but I'll close the PR.

**Pull request closed without merging**
