### PR TITLE
Modify css of "full-width-table"(#2409)

### PR DESCRIPTION
**Pull request by nerdchanii**
### linked issue(#2409)

Please refer to the issue for details.

### CODE REVIEW

**Review by orta — APPROVED** [review]

**Comment by nerdchanii** [comment]
@orta When will this merge? Is there anything else I should do?🙂

**Comment by orta** [comment]
That's on someone with merge access I'm afraid - this PR is fine as-is

**Comment by nerdchanii** [comment]
> That's on someone with merge access I'm afraid - this PR is fine as-is

Ah! Thank to your explaining 👍🏻

**Comment by vitaly-zdanevich** [comment]
Please attach a screenshots before / after.

**Comment by nerdchanii** [comment]
> Please attach a screenshots before / after.

There is in #2409

**Pull request closed without merging**
