### PR TITLE
Updates the site for 4.6

### PR DESCRIPTION
**Pull request by orta**
- Updates the site's TS to 4.6 
- Includes https://github.com/microsoft/TypeScript-Website/pull/2267
- Includes https://github.com/microsoft/TypeScript-Website/pull/2273

( and removes some .js files which weren't supposed to end up in the repo )

### CODE REVIEW

**Comment by orta** [comment]
I also did a run through of the 4.6 release notes and didn't see anything which felt like it needed raising in the core TS docs

**Comment by orta** [comment]
Assuming this greens, after a merge, you'll probably want to do a prod deploy ( https://github.com/microsoft/TypeScript-Website/actions/workflows/deploy-prod.yml ) so that the Playground defaults to 4.6 (or it will happen next monday)

**Comment by Andarist** [comment]
@andrewbranch since 4.6 has already been published - perhaps you would know how to best move forward with this right now.

**Comment by DanielRosenwasser** [comment]
Thank you!

**Comment by andrewbranch** [comment]
@orta I’m so happy, thank you 🥲 

Screen Shot 2022-03-07 at 9 26 08 AM

**Pull request merged**
