### PR TITLE
Add the 'index.node' resolution variety

### PR DESCRIPTION
**Pull request by Flamenco**
Add the 'index.node' variation for completeness.

If Typscript does NOT respect this, it should also be indicated.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
TS does not support this and I've never heard anyone ask about it either.

**Comment by Flamenco** [comment]
Then maybe you should school yourself @RyanCavanaugh , or allow a response.  It is CLEARY part of the node.js resolution.

https://www.typescriptlang.org/docs/handbook/module-resolution.html

**Comment by RyanCavanaugh** [comment]
It definitely is.

While the content is correct, the Handbook in particular requires a certain amount of brevity, and needs to maintain a tight focus on the most foundational aspects of TypeScript. This content might be better suited for an alternate documentation format with fewer scope constraints.

**Comment by Flamenco** [comment]
Well, given the detail that is stated in the current TS walkthough, adding the complete algorithm as implemented by node does not add much more.  

So I will leave it as that.  IMO it was an oversight, and should have been stated.  Hence my PR...

**Pull request closed without merging**
