### PR TITLE
[PT-BR] Tuples.ts

### PR DESCRIPTION
**Pull request by weltonfelix**
Hi, I have translated `Tuple.ts` from **playground** section.

@khaosdoctor, @alvarocamillont, @danilofuchs e @orta.

### CODE REVIEW

**Review by danilofuchs — APPROVED** [review]
LGTM

**Comment by danilofuchs** [comment]
LGTM (The merge action seems to be buggy atm)

**Comment by orta** [comment]
I guess the review webhook code isn't working

**Comment by khaosdoctor** [comment]
@weltonfelix Please update the spreadsheet on #233 so we know you finished :)

**Pull request merged**
