### PR TITLE
Update The Handbook.md

### PR DESCRIPTION
**Pull request by acmu**

### CODE REVIEW

**Comment by andrewbranch** [comment]
I don’t think this is a meaningful change. Would be open to a PR spelling out “object oriented” instead of using the acronym though.

**Comment by acmu** [comment]
> I don’t think this is a meaningful change. Would be open to a PR spelling out “object oriented” instead of using the acronym though.

I change that because of this:
image

image

page title and link title is not same,I think they should be same.

**Comment by andrewbranch** [comment]
Oh, I see. Which title is more recent according to `git blame`?

**Comment by acmu** [comment]
> Oh, I see. Which title is more recent according to `git blame`?

I can't distinguish which is recent, becaus they are same pull request and same time.

But according to article's content, I think it should be "TypeScript for Java/C# Programmers".

As for another, you can determine it.(I'm not good at English😅)

**Review by andrewbranch — APPROVED** [review]
Thanks for the explanation, this title seems to be more consistent.

**Pull request merged**
