### PR TITLE
Two files translated

### PR DESCRIPTION
**Pull request by herculesgabriel**
@khaosdoctor , @danilofuchs , @orta 

I just started translating, so more translations coming soon.

### CODE REVIEW

**Comment by khaosdoctor** [comment]
@herculesgabriel Thanks a lot for the contribution! Please take a look at #815 and #814 as some files you translated have already been translated by those PRs :) 

If possible, check and state which file you'll pickup to begin translation in #233 

One last thing, since you're creating a partial PR, can you please convert it back to draft? So we can analyse it once it's done?

**Comment by orta** [comment]
Poke @herculesgabriel

**Comment by herculesgabriel** [comment]
I'm so sorry for this huge delay. I got really busy last week. I'm pretty new at this too, so I'll try hard. Thank you for the help.

**Comment by herculesgabriel** [comment]
I'm not being able to convert it back to draft for some reason tough

**Comment by khaosdoctor** [comment]
I think that's because it's conflicting, can you resolve those, please?

**Pull request closed without merging**
