### PR TITLE
fix(handbook): Use correct import syntax

### PR DESCRIPTION
**Pull request by FlorianDr**
I believe this is a copy and paste error from the above line.

### CODE REVIEW

**Comment by orta** [comment]
Oddly enough, this is not wrong: http://www.staging-typescript.org/play/?module=1#code/JYWwDg9gTgLgBAMwM5wLxygUwI4FdhYAUARMsQJQDcAUNcgHRYCGAJgGLAA2mAygJ4A7akA ( if you give it a second to download the node d.ts files you'll see it correctly fail )

**Comment by orta** [comment]
Whether it's something we should encourage anymore is a different question, which I'm not sure of yet, will ask around

**Comment by FlorianDr** [comment]
@orta thank you for getting back to me so fast. As a reader, I was confused to find this syntax, because it's referencing ES6 in the line above and I was expecting ES6 modules import syntax.

**Comment by FlorianDr** [comment]
@orta do you have any updates regarding this one?

**Comment by FlorianDr** [comment]
@orta I will close this PR for now. Let me know, if there are any changes.

**Pull request closed without merging**
