### PR TITLE
Add Indonesian language translation for newLine

### PR DESCRIPTION
**Pull request by mul14**

### CODE REVIEW

**Review by SMAKSS — COMMENTED** [review]
Thank you for the PR, but I believe you translate the actual English files, which is not necessary. If you want to contribute to the Indonesian translation please do follow #938 and pick a proper task from the remaining ones.

**Comment by orta** [comment]
Yep, agree - this PR would need changes (new Indonesian file) to be merged

**Comment by orta** [comment]
Poke @mul14 - you can still do this! Otherwise I'll close this PR at the end of the week, because we're moving these PRs into their own repos re: https://github.com/microsoft/TypeScript-Website/issues/1480

**Comment by orta** [comment]
Sorry @mul14 - I'm going to close this PR, I'd love to see this get re-created on the new repo though!

https://github.com/microsoft/TypeScript-Website-Localizations

**Pull request closed without merging**
