### PR TITLE
fix example imports

### PR DESCRIPTION
**Pull request by frankie303**

### CODE REVIEW

**Comment by jakebailey** [comment]
Why change this? Extensions are legal, and even required in newer module modes.

**Comment by frankie303** [comment]
@jakebailey I didn't know that js files can include types (in example, type is imported from js file). So I thought that was a mistake.

**Comment by jakebailey** [comment]
TypeScript doesn't rewrite extensions; an import may say .js but point to a TS file, or that file may be .js but contain JSDoc or inferred types under allowJs.

**Comment by frankie303** [comment]
Thank you so much for the explanation!

**Pull request closed without merging**
