### PR TITLE
Fix getting LSP result

### PR DESCRIPTION
**Pull request by falinsky**

### CODE REVIEW

**Comment by orta** [comment]
Perfect, I should maybe make these fail the build in the future

**Comment by falinsky** [comment]
> Perfect, I should maybe make these fail the build in the future

@orta Yeah, makes sense. As far as I saw there were quite a few similar places. Meanwhile, I'm thinking about crawling all the pages, finding similar places with issues, and fix them all at once.

**Comment by ghost** [comment]
[CLA assistant check](https://cla.opensource.microsoft.com/microsoft/TypeScript-Website?pullRequest=1528) <br/>All CLA requirements met.

**Comment by falinsky** [comment]
@orta checked all the pages under the [https://www.typescriptlang.org/docs](https://www.typescriptlang.org/docs) prefix.

**Comment by orta** [comment]
Great! Thanks!

**Pull request merged**
