### PR TITLE
fix: allow overflow on code snippets for tooltips

### LINKED ISSUE #2506: Docs: (css) code snippets tooltip overflow cuts of contents
when browsing the handbook and hovering over type annotations in the code snippets, the container cuts of content due to overflow.

image

**Page URL:** 
https://www.typescriptlang.org/docs/handbook/2/conditional-types.html

**Issue:** 
see image

**Recommended Fix:** 
PR inc

### PR DESCRIPTION
**Pull request by kitsunekyo**
fixes #2506

allow overflow on code snippet container, to show type annotation tooltip correctly. 

the other changes are just prettier autoformat. i can revert these if preferred.

### CODE REVIEW

**Comment by orta** [comment]
Nice work

Reviewers: I'd run this and check that this doesn't start showing scrollbars in strange places on windows/linux

**Comment by kitsunekyo** [comment]
any update on this?

**Comment by jakebailey** [comment]
The PR currently has conflicts, but I'm happy to try and take a look locally to verify that it doesn't break things.

**Comment by jakebailey** [comment]
Looks good: 
image

No weird scrollbars.

**Review by jakebailey — APPROVED** [review]

**Pull request merged**
